### ISSUE TITLE
要是和N_m3u8DL-CLI一样支持自定义请求头就好了

### ISSUE THREAD

**Issue by pmoled** [charleszhang97/93.Ye.M3U8.Downloader#1]
要是和N_m3u8DL-CLI一样支持自定义请求头就好了

**Comment by charleszhang97** [comment]
如果是外部调用，使用参数aria2c-args-append="--header=\\"Origin:XXX\\" --header=\\"Referer:XXX\\""传入headers；如果是程序UI，参数追加填入--header="Origin:XXX" --header="Referer:XXX"；第三种，直接写在配置文件中，Aria2\xxx.conf，写入两行header="Origin:XXX" header="Referer:XXX"。[参考aria2的--header参数](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-header)

**Comment by charleszhang97** [comment]
> 如果是外部调用，使用参数aria2c-args-append="--header=\"Origin:XXX\" --header=\"Referer:XXX\""传入headers；如果是程序UI，参数追加填入--header="Origin:XXX" --header="Referer:XXX"；第三种，直接写在配置文件中，Aria2\xxx.conf，写入两行header="Origin:XXX" header="Referer:XXX"。[参考aria2的--header参数](https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-header)

纠正一下我自己的说法。写在配置文件里的请求头，不能带引号，否则Server会返回Bad request，正确格式：header=Origin:XXX
